In [154]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2+cu121


In [155]:
!nvidia-smi

Fri Jan  5 01:46:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   39C    P2              51W / 450W |   1816MiB / 24564MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to Tensors

### Creating tensors

In [156]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [157]:
scalar.ndim

0

In [158]:
# Get tensor back as Python int
scalar.item()

7

In [159]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [160]:
vector.ndim

1

In [161]:
vector.shape

torch.Size([2])

In [162]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [163]:
MATRIX.ndim

2

In [164]:
MATRIX[1]

tensor([ 9, 10])

In [165]:
MATRIX.shape

torch.Size([2, 2])

In [166]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [167]:
TENSOR.ndim

3

In [168]:
TENSOR.shape

torch.Size([1, 3, 3])

In [169]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [170]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [171]:
random_tensor.ndim

2

In [172]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [173]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [174]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [175]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [176]:
ones.dtype

torch.float32

In [177]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [178]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [179]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [180]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [181]:
float_32_tensor.dtype

torch.float32

In [182]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [183]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [184]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [185]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. to get datatype from a tensor, can use `tensor.dtype`
2. to get shape from a tensor, can use `tensor.shape`
3. to get device from a tensor, can use `tensor.device`

In [186]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [187]:
# Find out details about some tensor
print(some_tensor)
print(f"Datetype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Datetype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [188]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [189]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [190]:
tensor

tensor([1, 2, 3])

In [191]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [192]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [193]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

* Element-wise multiplication
* Matrix multiplication (dot-product)

In [194]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [195]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [196]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [197]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [198]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3) -> (3, 3)` will work
* `(2, 3) @ (3, 2) -> (2, 2)` will work

In [199]:
torch.rand(3, 2).shape

torch.Size([3, 2])

In [200]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))  

tensor([[0.9870, 1.0960],
        [1.0158, 0.7339]])

In [201]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
# torch.matmul(tensor_A, tensor_B) # this doesn't work, wrong shape


In [202]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [203]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [204]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [205]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [206]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [207]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [208]:
# Find the mean - note: requires tensor type to be float
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [209]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [210]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [211]:
# Find the position in tensor that has the min value with argmin() - note: returns first index if multiple min values
x.argmin()

tensor(0)

In [212]:
x[0]

tensor(1)

In [213]:
# Find the position in tensor that has the max value with argmax() - note: returns first index if multiple max values
x.argmax()

tensor(9)

In [214]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [215]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [216]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [217]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [218]:
# Changing z changes x because they point to the same place in memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [219]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [220]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [221]:
#torch.unsqueeze() - adds a dimension of 1 to a target tensor
print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")

# Add extra dimensions to x
x_unsqueezed = x.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [222]:
# torch.permute() - shuffle dimensions of a tensor
x_original = torch.rand(size=(224, 224, 3))

# Permute tensor dimensions
x_permuted = x_original.permute(2, 0, 1) # change from (224, 224, 3) to (3, 224, 224)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [223]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [224]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [225]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [226]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [227]:
# Let's index on the inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [228]:
# You can also use ":" to select all items in a given dimension
x[:, 0]

tensor([[1, 2, 3]])

In [229]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [230]:
# Get all values of the 0 dimension but only index 1 and 2 of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [231]:
# Get index 0 of 0th and 1st dimensions but all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [232]:
# Index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])


tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

Data Type is different
Tensors dtype = float32
Numpy dtype = float64

In [233]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [234]:
# Change the value of array, what happens to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [235]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [236]:
# Change the value of tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

**random seed**

In [237]:
# Create two random tensors
random_1 = torch.rand(3, 4)
random_2 = torch.rand(3, 4)

print(random_1)
print(random_2)
print(random_1 == random_2)

tensor([[0.2313, 0.2927, 0.3386, 0.3708],
        [0.0831, 0.0944, 0.6568, 0.7708],
        [0.1053, 0.1467, 0.1932, 0.9118]])
tensor([[0.1488, 0.0913, 0.4470, 0.2440],
        [0.5571, 0.1928, 0.0602, 0.5837],
        [0.0009, 0.7581, 0.5817, 0.4338]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [238]:
# Let's make some random but reproducible tensors
# Set seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_3 = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_4 = torch.rand(3, 4)

print(random_3)
print(random_4)
print(random_3 == random_4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [239]:
torch.cuda.is_available()

True

In [240]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [241]:
torch.cuda.device_count()

1

In [242]:
# Create a tensor for the CPU
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [243]:
# Create a tensor for the GPU
tensor_on_gpu = torch.tensor([1, 2, 3]).to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [246]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy()
# To fix this, we can move the tensor back to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [247]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')